server:
  port: 10011
  
spring:
  redis:
    host: 192.168.1.60
    port: 6379
    password: 

ignore:
  urls:
    - /**/*.css
    - /login
    - /oauth/**
    - /auth/oauth/**
    - /actuator/**
    - /hystrix/**
    - /swagger-resource/**
    - /swagger-ui.html/**
    - /webjars/**
    - /swagger-resources/**
    - /v2/api-docs 
    - /rscLogin
    - /captcha.jpg
    - /subscripcenter/**
    - /newscenter/**
    - /fulltextsearch/**
    - /keyboardsearch/**
    - /info/**
    - /dataconver/**